---
- name: Install git
  apt: name=git state=installed

- name: Install tree
  apt: name=tree state=installed

- name: Install ag
  apt: name=silversearcher-ag state=installed

- name: Install jq
  apt: name=jq state=installed

- name: Install autojump
  apt: name=autojump state=installed
  register: autojump_status

- name: Install vim
  apt: name=vim state=installed

- name: Install unzip
  apt: name=unzip state=installed

- name: copy autojump profile
  copy:
    src=/usr/share/autojump/autojump.sh
    dest=/etc/profile.d/autojump.sh
  when: autojump_status.changed

# utilities are installed as specified user
- name: pull fzf repository
  git:
    repo=https://github.com/junegunn/fzf.git
    dest=~/.fzf
    depth=1
  register: fzf_status
  become_user: ubuntu

#- name: install fzf
#  command: "~/.fzf/install --all"
#  when: fzf_status.changed
#  become_user: ubuntu

- name: install bash_it for better bash
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: ~/.bash_it
    depth: 1
  become_user: ubuntu
